# https://just-the-docs.com/

title: HALchemy
email: michael@pointw.com
logo: /assets/img/halchemy.png
# favicon_ico: 
baseurl: halchemy
description: >- 
  HAL-based Hypermedia API clients for humans.

theme: just-the-docs
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-tabs


color_scheme: dark
