# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in halchemy.gemspec
gemspec

gem "cicphash", "~> 2.0"
gem "http_status_codes", "~> 0.1.0"
gem "httpx", "~> 1.4"
gem "json", "~> 2.9.1"

gem "logger", "~> 1.6.0"

group :dev do
  gem "rake", "~> 13.0"
  gem "rubocop", "~> 1.21"
end

group :test do
  gem "cucumber", "~> 9.2.1"
  gem "rspec", "~> 3.13.0"
  gem "webmock", "~> 3.24.0"
end
