module Halchemy
  class BaseRequester
    @_data: Object | nil
    @_headers: CICPHash
    @_is_templated: bool
    @_parameters: Hash[String, Object]
    @_template_values: Hash[String, Object]
    @_url: String
    @api: Api
    @resource: Resource | HalResource

    def request: -> (Resource | HalResource)

    def url: -> String

    def with_headers: -> (BaseRequester | ReadOnlyRequester | Requester)

    def with_parameters: -> (BaseRequester | ReadOnlyRequester | Requester)

    def with_template_values: -> (BaseRequester | ReadOnlyRequester | Requester)
  end
end
