module Halchemy
  class BaseRequester
    LIST_STYLE_HANDLERS: Hash[String, Object]

    @_data: Object | nil
    @_headers: CICPHash
    @_is_templated: bool
    @_parameters: Hash[String, Object]
    @_template_values: Hash[String, Object]
    @_url: String
    @api: Api
    @resource: Resource | HalResource

    def initialize: -> void

    def request: -> (Resource | HalResource)

    def url: -> String

    def with_headers: -> (BaseRequester | ReadOnlyRequester | Requester)

    def with_parameters: -> (BaseRequester | ReadOnlyRequester | Requester)

    def with_template_values: -> (BaseRequester | ReadOnlyRequester | Requester)

    private

    def add_parameters_to_url: -> String

    def flatten_parameters: -> Array[String]

    def handle_list: -> Array[Object]

    def process_target: -> void

  end
end
